class OwnerV3:
    name: str
    age: int
    def __init__(self) -> None: ...
    def get_name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def get_age(self) -> int: ...
    def set_age(self, age: int) -> None: ...
    def freeze(self) -> str: ...
    def melt(self, src: str) -> int: ... 