from typing import Any, List

class Owner:
    name: str
    age: int

    def __init__(self) -> None: ...
    def get_name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def get_age(self) -> int: ...
    def set_age(self, age: int) -> None: ...

class Pet:
    own: Owner
    arr_own: List[Owner]
    vec_own: List[Owner]
    d: float
    f: float
    i32: int
    i64: int
    u32: int
    u64: int
    bval: bool
    s: str
    arr_d: List[float]
    arr_f: List[float]
    arr_i32: List[int]
    arr_i64: List[int]
    arr_u32: List[int]
    arr_u64: List[int]
    arr_bval: List[bool]
    arr_s: List[str]
    vec_d: List[float]
    vec_f: List[float]
    vec_i32: List[int]
    vec_i64: List[int]
    vec_u32: List[int]
    vec_u64: List[int]
    vec_bval: List[bool]
    vec_s: List[str]

    def __init__(self) -> None: ...
    def bark(self) -> None: ...
    def get_d(self) -> float: ...
    def set_d(self, val: float) -> None: ...
    def get_f(self) -> float: ...
    def set_f(self, val: float) -> None: ...
    def get_i32(self) -> int: ...
    def set_i32(self, val: int) -> None: ...
    def get_i64(self) -> int: ...
    def set_i64(self, val: int) -> None: ...
    def get_u32(self) -> int: ...
    def set_u32(self, val: int) -> None: ...
    def get_u64(self) -> int: ...
    def set_u64(self, val: int) -> None: ...
    def get_bval(self) -> bool: ...
    def set_bval(self, val: bool) -> None: ...
    def get_s(self) -> str: ...
    def set_s(self, val: str) -> None: ...
    def get_arr_d(self) -> List[float]: ...
    def set_arr_d(self, val: List[float]) -> None: ...
    def get_arr_f(self) -> List[float]: ...
    def set_arr_f(self, val: List[float]) -> None: ...
    def get_arr_i32(self) -> List[int]: ...
    def set_arr_i32(self, val: List[int]) -> None: ...
    def get_arr_i64(self) -> List[int]: ...
    def set_arr_i64(self, val: List[int]) -> None: ...
    def get_arr_u32(self) -> List[int]: ...
    def set_arr_u32(self, val: List[int]) -> None: ...
    def get_arr_u64(self) -> List[int]: ...
    def set_arr_u64(self, val: List[int]) -> None: ...
    def get_arr_bval(self) -> List[bool]: ...
    def set_arr_bval(self, val: List[bool]) -> None: ...
    def get_arr_s(self) -> List[str]: ...
    def set_arr_s(self, val: List[str]) -> None: ...
    def get_vec_d(self) -> List[float]: ...
    def set_vec_d(self, val: List[float]) -> None: ...
    def get_vec_f(self) -> List[float]: ...
    def set_vec_f(self, val: List[float]) -> None: ...
    def get_vec_i32(self) -> List[int]: ...
    def set_vec_i32(self, val: List[int]) -> None: ...
    def get_vec_i64(self) -> List[int]: ...
    def set_vec_i64(self, val: List[int]) -> None: ...
    def get_vec_u32(self) -> List[int]: ...
    def set_vec_u32(self, val: List[int]) -> None: ...
    def get_vec_u64(self) -> List[int]: ...
    def set_vec_u64(self, val: List[int]) -> None: ...
    def get_vec_bval(self) -> List[bool]: ...
    def set_vec_bval(self, val: List[bool]) -> None: ...
    def get_vec_s(self) -> List[str]: ...
    def set_vec_s(self, val: List[str]) -> None: ...
    def get_own(self) -> Owner: ...
    def set_own(self, val: Owner) -> None: ...
    def get_arr_own(self) -> List[Owner]: ...
    def set_arr_own(self, val: List[Owner]) -> None: ...
    def get_vec_own(self) -> List[Owner]: ...
    def set_vec_own(self, val: List[Owner]) -> None: ...
    def freeze(self) -> bytes: ...
    def melt(self, src: bytes) -> None: ...
