from typing import List, Any

class Owner:
    name_: str
    age_: int

    def __init__(self) -> None: ...
    def getName(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def getAge(self) -> int: ...
    def setAge(self, age: int) -> None: ...

class Pet:
    name: str
    age: int
    weight: float
    height: float
    isVaccinated: bool
    gender: str
    favoriteNumbers: list[int]
    coordinates: list[float]
    tricks: list[str]
    scores: list[int]
    owner: Owner
    multipleOwners: list[Owner]
    ownerList: list[Owner]

    def __init__(self) -> None: ...
    def __init__(self, ptr: Any) -> None: ...
    @staticmethod
    def from_address(addr: int) -> "Pet": ...
    def bark(self) -> None: ...
    def getName(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def getAge(self) -> int: ...
    def setAge(self, age: int) -> None: ...
    def getWeight(self) -> float: ...
    def setWeight(self, weight: float) -> None: ...
    def getHeight(self) -> float: ...
    def setHeight(self, height: float) -> None: ...
    def getIsVaccinated(self) -> bool: ...
    def setIsVaccinated(self, v: bool) -> None: ...
    def getGender(self) -> str: ...
    def setGender(self, g: str) -> None: ...
    def getFavoriteNumbers(self) -> list[int]: ...
    def setFavoriteNumbers(self, fn: list[int]) -> None: ...
    def getCoordinates(self) -> list[float]: ...
    def setCoordinates(self, c: list[float]) -> None: ...
    def getTricks(self) -> list[str]: ...
    def setTricks(self, t: list[str]) -> None: ...
    def getScores(self) -> list[int]: ...
    def setScores(self, s: list[int]) -> None: ...
    def getOwner(self) -> Owner: ...
    def setOwner(self, o: Owner) -> None: ...
    def getMultipleOwners(self) -> list[Owner]: ...
    def setMultipleOwners(self, mo: list[Owner]) -> None: ...
    def getOwnerList(self) -> list[Owner]: ...
    def setOwnerList(self, ol: list[Owner]) -> None: ...
    def serialize(self) -> bytes: ...
    def deserialize(self, src: bytes) -> None: ... 