#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "roboticfluid_cpp/rf_pet/pet.hpp"
#include "roboticfluid_cpp/owner_v4.hpp"

namespace rf_pet {

void init_type_pet(pybind11::module_ &m) {
    pybind11::class_<Pet>(m, "Pet")
        .def(pybind11::init<>())
        .def_readwrite("own", &Pet::own)
        .def_readwrite("arr_own", &Pet::arr_own)
        .def_readwrite("vec_own", &Pet::vec_own)
        .def_readwrite("own_v2", &Pet::own_v2)
        .def_readwrite("arr_own_v2", &Pet::arr_own_v2)
        .def_readwrite("vec_own_v2", &Pet::vec_own_v2)
        .def_readwrite("own_v3", &Pet::own_v3)
        .def_readwrite("arr_own_v3", &Pet::arr_own_v3)
        .def_readwrite("vec_own_v3", &Pet::vec_own_v3)
        .def_readwrite("own_v4", &Pet::own_v4)
        .def_readwrite("arr_own_v4", &Pet::arr_own_v4)
        .def_readwrite("vec_own_v4", &Pet::vec_own_v4)
        .def_readwrite("pet_type", &Pet::pet_type)
        .def_readwrite("arr_pet_type", &Pet::arr_pet_type)
        .def_readwrite("vec_pet_type", &Pet::vec_pet_type)
        .def_readwrite("arr_u8", &Pet::arr_u8)
        .def_readwrite("d", &Pet::d)
        .def_readwrite("f", &Pet::f)
        .def_readwrite("i32", &Pet::i32)
        .def_readwrite("i64", &Pet::i64)
        .def_readwrite("u32", &Pet::u32)
        .def_readwrite("u64", &Pet::u64)
        .def_readwrite("bval", &Pet::bval)
        .def_readwrite("s", &Pet::s)
        .def_readwrite("arr_d", &Pet::arr_d)
        .def_readwrite("arr_f", &Pet::arr_f)
        .def_readwrite("arr_i32", &Pet::arr_i32)
        .def_readwrite("arr_i64", &Pet::arr_i64)
        .def_readwrite("arr_u32", &Pet::arr_u32)
        .def_readwrite("arr_u64", &Pet::arr_u64)
        .def_readwrite("arr_bval", &Pet::arr_bval)
        .def_readwrite("arr_s", &Pet::arr_s)
        .def_readwrite("vec_d", &Pet::vec_d)
        .def_readwrite("vec_f", &Pet::vec_f)
        .def_readwrite("vec_i32", &Pet::vec_i32)
        .def_readwrite("vec_i64", &Pet::vec_i64)
        .def_readwrite("vec_u32", &Pet::vec_u32)
        .def_readwrite("vec_u64", &Pet::vec_u64)
        .def_readwrite("vec_bval", &Pet::vec_bval)
        .def_readwrite("vec_s", &Pet::vec_s)
        .def("bark", &Pet::bark)
        .def("dump", [](const Pet& pet) {
            std::vector<uint8_t> out;
            pet.dump(out);
            return pybind11::bytes(reinterpret_cast<const char*>(out.data()), out.size());
        })
        .def("load", [](Pet& pet, const pybind11::bytes& src) {
            std::string s = static_cast<std::string>(src);
            std::vector<uint8_t> buf(s.begin(), s.end());
            pet.load(buf);
        })
        .def("dump_compressed", [](const Pet& pet) {
            std::vector<uint8_t> out;
            pet.dump_compressed(out);
            return pybind11::bytes(reinterpret_cast<const char*>(out.data()), out.size());
        })
        .def("load_compressed", [](Pet& pet, const pybind11::bytes& src) {
            std::string s = static_cast<std::string>(src);
            std::vector<uint8_t> buf(s.begin(), s.end());
            return pet.load_compressed(buf);
        })
        .def("get_own", &Pet::get_own)
        .def("set_own", &Pet::set_own)
        .def("get_arr_own", &Pet::get_arr_own, pybind11::return_value_policy::reference_internal)
        .def("set_arr_own", &Pet::set_arr_own)
        .def("get_vec_own", &Pet::get_vec_own, pybind11::return_value_policy::reference_internal)
        .def("set_vec_own", &Pet::set_vec_own)
        .def("get_own_v2", &Pet::get_own_v2)
        .def("set_own_v2", &Pet::set_own_v2)
        .def("get_arr_own_v2", &Pet::get_arr_own_v2, pybind11::return_value_policy::reference_internal)
        .def("set_arr_own_v2", &Pet::set_arr_own_v2)
        .def("get_vec_own_v2", &Pet::get_vec_own_v2, pybind11::return_value_policy::reference_internal)
        .def("set_vec_own_v2", &Pet::set_vec_own_v2)
        .def("get_own_v3", &Pet::get_own_v3)
        .def("set_own_v3", &Pet::set_own_v3)
        .def("get_arr_own_v3", &Pet::get_arr_own_v3, pybind11::return_value_policy::reference_internal)
        .def("set_arr_own_v3", &Pet::set_arr_own_v3)
        .def("get_vec_own_v3", &Pet::get_vec_own_v3, pybind11::return_value_policy::reference_internal)
        .def("set_vec_own_v3", &Pet::set_vec_own_v3)
        .def("get_own_v4", &Pet::get_own_v4)
        .def("set_own_v4", &Pet::set_own_v4)
        .def("get_arr_own_v4", &Pet::get_arr_own_v4, pybind11::return_value_policy::reference_internal)
        .def("set_arr_own_v4", &Pet::set_arr_own_v4)
        .def("get_vec_own_v4", &Pet::get_vec_own_v4, pybind11::return_value_policy::reference_internal)
        .def("set_vec_own_v4", &Pet::set_vec_own_v4)
        .def("get_pet_type", &Pet::get_pet_type)
        .def("set_pet_type", &Pet::set_pet_type)
        .def("get_arr_pet_type", &Pet::get_arr_pet_type, pybind11::return_value_policy::reference_internal)
        .def("set_arr_pet_type", &Pet::set_arr_pet_type)
        .def("get_vec_pet_type", &Pet::get_vec_pet_type, pybind11::return_value_policy::reference_internal)
        .def("set_vec_pet_type", &Pet::set_vec_pet_type)
        .def("get_arr_u8", &Pet::get_arr_u8, pybind11::return_value_policy::reference_internal)
        .def("set_arr_u8", &Pet::set_arr_u8)
        .def("get_d", &Pet::get_d)
        .def("set_d", &Pet::set_d)
        .def("get_f", &Pet::get_f)
        .def("set_f", &Pet::set_f)
        .def("get_i32", &Pet::get_i32)
        .def("set_i32", &Pet::set_i32)
        .def("get_i64", &Pet::get_i64)
        .def("set_i64", &Pet::set_i64)
        .def("get_u32", &Pet::get_u32)
        .def("set_u32", &Pet::set_u32)
        .def("get_u64", &Pet::get_u64)
        .def("set_u64", &Pet::set_u64)
        .def("get_bval", &Pet::get_bval)
        .def("set_bval", &Pet::set_bval)
        .def("get_s", &Pet::get_s)
        .def("set_s", &Pet::set_s)
        .def("get_arr_d", &Pet::get_arr_d, pybind11::return_value_policy::reference_internal)
        .def("set_arr_d", &Pet::set_arr_d)
        .def("get_arr_f", &Pet::get_arr_f, pybind11::return_value_policy::reference_internal)
        .def("set_arr_f", &Pet::set_arr_f)
        .def("get_arr_i32", &Pet::get_arr_i32, pybind11::return_value_policy::reference_internal)
        .def("set_arr_i32", &Pet::set_arr_i32)
        .def("get_arr_i64", &Pet::get_arr_i64, pybind11::return_value_policy::reference_internal)
        .def("set_arr_i64", &Pet::set_arr_i64)
        .def("get_arr_u32", &Pet::get_arr_u32, pybind11::return_value_policy::reference_internal)
        .def("set_arr_u32", &Pet::set_arr_u32)
        .def("get_arr_u64", &Pet::get_arr_u64, pybind11::return_value_policy::reference_internal)
        .def("set_arr_u64", &Pet::set_arr_u64)
        .def("get_arr_bval", &Pet::get_arr_bval, pybind11::return_value_policy::reference_internal)
        .def("set_arr_bval", &Pet::set_arr_bval)
        .def("get_arr_s", &Pet::get_arr_s, pybind11::return_value_policy::reference_internal)
        .def("set_arr_s", &Pet::set_arr_s)
        .def("get_vec_d", &Pet::get_vec_d, pybind11::return_value_policy::reference_internal)
        .def("set_vec_d", &Pet::set_vec_d)
        .def("get_vec_f", &Pet::get_vec_f, pybind11::return_value_policy::reference_internal)
        .def("set_vec_f", &Pet::set_vec_f)
        .def("get_vec_i32", &Pet::get_vec_i32, pybind11::return_value_policy::reference_internal)
        .def("set_vec_i32", &Pet::set_vec_i32)
        .def("get_vec_i64", &Pet::get_vec_i64, pybind11::return_value_policy::reference_internal)
        .def("set_vec_i64", &Pet::set_vec_i64)
        .def("get_vec_u32", &Pet::get_vec_u32, pybind11::return_value_policy::reference_internal)
        .def("set_vec_u32", &Pet::set_vec_u32)
        .def("get_vec_u64", &Pet::get_vec_u64, pybind11::return_value_policy::reference_internal)
        .def("set_vec_u64", &Pet::set_vec_u64)
        .def("get_vec_bval", &Pet::get_vec_bval, pybind11::return_value_policy::reference_internal)
        .def("set_vec_bval", &Pet::set_vec_bval)
        .def("get_vec_s", &Pet::get_vec_s, pybind11::return_value_policy::reference_internal)
        .def("set_vec_s", &Pet::set_vec_s);
}

} // namespace rf_pet 