#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include "shared_struct.hpp"

namespace py = pybind11;

PYBIND11_MODULE(rf_pet, m) {
    py::class_<rf_pet::Pet>(m, "Pet")
        .def(py::init<>())
        .def_readwrite("own", &rf_pet::Pet::own)
        .def_readwrite("arr_own", &rf_pet::Pet::arr_own)
        .def_readwrite("vec_own", &rf_pet::Pet::vec_own)
        .def_readwrite("d", &rf_pet::Pet::d)
        .def_readwrite("f", &rf_pet::Pet::f)
        .def_readwrite("i32", &rf_pet::Pet::i32)
        .def_readwrite("i64", &rf_pet::Pet::i64)
        .def_readwrite("u32", &rf_pet::Pet::u32)
        .def_readwrite("u64", &rf_pet::Pet::u64)
        .def_readwrite("bval", &rf_pet::Pet::bval)
        .def_readwrite("s", &rf_pet::Pet::s)
        .def_readwrite("arr_d", &rf_pet::Pet::arr_d)
        .def_readwrite("arr_f", &rf_pet::Pet::arr_f)
        .def_readwrite("arr_i32", &rf_pet::Pet::arr_i32)
        .def_readwrite("arr_i64", &rf_pet::Pet::arr_i64)
        .def_readwrite("arr_u32", &rf_pet::Pet::arr_u32)
        .def_readwrite("arr_u64", &rf_pet::Pet::arr_u64)
        .def_readwrite("arr_bval", &rf_pet::Pet::arr_bval)
        .def_readwrite("arr_s", &rf_pet::Pet::arr_s)
        .def_readwrite("vec_d", &rf_pet::Pet::vec_d)
        .def_readwrite("vec_f", &rf_pet::Pet::vec_f)
        .def_readwrite("vec_i32", &rf_pet::Pet::vec_i32)
        .def_readwrite("vec_i64", &rf_pet::Pet::vec_i64)
        .def_readwrite("vec_u32", &rf_pet::Pet::vec_u32)
        .def_readwrite("vec_u64", &rf_pet::Pet::vec_u64)
        .def_readwrite("vec_bval", &rf_pet::Pet::vec_bval)
        .def_readwrite("vec_s", &rf_pet::Pet::vec_s)
        .def("bark", &rf_pet::Pet::bark)
        .def("freeze", [](const rf_pet::Pet& pet) { return py::bytes(pet.freeze()); })
        .def("melt", [](rf_pet::Pet& pet, const py::bytes& src) {
            pet.melt(std::string(src));
        })
        .def("get_own", &rf_pet::Pet::get_own)
        .def("set_own", &rf_pet::Pet::set_own)
        .def("get_arr_own", &rf_pet::Pet::get_arr_own, py::return_value_policy::reference_internal)
        .def("set_arr_own", &rf_pet::Pet::set_arr_own)
        .def("get_vec_own", &rf_pet::Pet::get_vec_own, py::return_value_policy::reference_internal)
        .def("set_vec_own", &rf_pet::Pet::set_vec_own)
        .def("get_d", &rf_pet::Pet::get_d)
        .def("set_d", &rf_pet::Pet::set_d)
        .def("get_f", &rf_pet::Pet::get_f)
        .def("set_f", &rf_pet::Pet::set_f)
        .def("get_i32", &rf_pet::Pet::get_i32)
        .def("set_i32", &rf_pet::Pet::set_i32)
        .def("get_i64", &rf_pet::Pet::get_i64)
        .def("set_i64", &rf_pet::Pet::set_i64)
        .def("get_u32", &rf_pet::Pet::get_u32)
        .def("set_u32", &rf_pet::Pet::set_u32)
        .def("get_u64", &rf_pet::Pet::get_u64)
        .def("set_u64", &rf_pet::Pet::set_u64)
        .def("get_bval", &rf_pet::Pet::get_bval)
        .def("set_bval", &rf_pet::Pet::set_bval)
        .def("get_s", &rf_pet::Pet::get_s)
        .def("set_s", &rf_pet::Pet::set_s)
        .def("get_arr_d", &rf_pet::Pet::get_arr_d, py::return_value_policy::reference_internal)
        .def("set_arr_d", &rf_pet::Pet::set_arr_d)
        .def("get_arr_f", &rf_pet::Pet::get_arr_f, py::return_value_policy::reference_internal)
        .def("set_arr_f", &rf_pet::Pet::set_arr_f)
        .def("get_arr_i32", &rf_pet::Pet::get_arr_i32, py::return_value_policy::reference_internal)
        .def("set_arr_i32", &rf_pet::Pet::set_arr_i32)
        .def("get_arr_i64", &rf_pet::Pet::get_arr_i64, py::return_value_policy::reference_internal)
        .def("set_arr_i64", &rf_pet::Pet::set_arr_i64)
        .def("get_arr_u32", &rf_pet::Pet::get_arr_u32, py::return_value_policy::reference_internal)
        .def("set_arr_u32", &rf_pet::Pet::set_arr_u32)
        .def("get_arr_u64", &rf_pet::Pet::get_arr_u64, py::return_value_policy::reference_internal)
        .def("set_arr_u64", &rf_pet::Pet::set_arr_u64)
        .def("get_arr_bval", &rf_pet::Pet::get_arr_bval, py::return_value_policy::reference_internal)
        .def("set_arr_bval", &rf_pet::Pet::set_arr_bval)
        .def("get_arr_s", &rf_pet::Pet::get_arr_s, py::return_value_policy::reference_internal)
        .def("set_arr_s", &rf_pet::Pet::set_arr_s)
        .def("get_vec_d", &rf_pet::Pet::get_vec_d, py::return_value_policy::reference_internal)
        .def("set_vec_d", &rf_pet::Pet::set_vec_d)
        .def("get_vec_f", &rf_pet::Pet::get_vec_f, py::return_value_policy::reference_internal)
        .def("set_vec_f", &rf_pet::Pet::set_vec_f)
        .def("get_vec_i32", &rf_pet::Pet::get_vec_i32, py::return_value_policy::reference_internal)
        .def("set_vec_i32", &rf_pet::Pet::set_vec_i32)
        .def("get_vec_i64", &rf_pet::Pet::get_vec_i64, py::return_value_policy::reference_internal)
        .def("set_vec_i64", &rf_pet::Pet::set_vec_i64)
        .def("get_vec_u32", &rf_pet::Pet::get_vec_u32, py::return_value_policy::reference_internal)
        .def("set_vec_u32", &rf_pet::Pet::set_vec_u32)
        .def("get_vec_u64", &rf_pet::Pet::get_vec_u64, py::return_value_policy::reference_internal)
        .def("set_vec_u64", &rf_pet::Pet::set_vec_u64)
        .def("get_vec_bval", &rf_pet::Pet::get_vec_bval, py::return_value_policy::reference_internal)
        .def("set_vec_bval", &rf_pet::Pet::set_vec_bval)
        .def("get_vec_s", &rf_pet::Pet::get_vec_s, py::return_value_policy::reference_internal)
        .def("set_vec_s", &rf_pet::Pet::set_vec_s);
} 